modules/blog/models/Article.php
<?php

namespace app\modules\blog\models;

use dektrium\user\models\User;
use dosamigos\taggable\Taggable;
use Yii;
use yii\bootstrap\Html;
use yii\behaviors\SluggableBehavior;

/**
 * This is the model class for table "{{%blog_articles}}".
 *
 * @property int $id ID
 * @property int $author_id Автор
 * @property int $category_id Категория
 * @property int $image Изображение
 * @property int $is_commentable Разрешено комментировать
 * @property int $is_enabled Включено
 * @property string $title Заголовок
 * @property string $slug Алиас
 * @property string $annotation Аннотация
 * @property string $text Текст
 * @property string $meta_title Заголовок для поисковика
 * @property string $keywords Метатеги. Ключевые слова
 * @property string $description Метатеги. Описание
 * @property string $created_at Создано
 * @property string $updated_at Обновлено

 * @property User $author Автор
 * @property Category $category Категория
 * @property Tag[] $tags Теги
 */
class Article extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%blog_article}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['author_id', 'category_id', 'is_commentable', 'is_enabled'], 'integer'],
            [['is_commentable', 'title', 'text', 'category'], 'required'],
            [['annotation', 'text'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['title','meta_title', 'slug', 'keywords', 'description', 'image', 'category'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            [['tagNames'], 'safe'],
            [['file'], 'safe'],
            [['file'], 'file', 'extensions'=>'jpg, jpeg, gif, png'],
            [['file'], 'file', 'maxSize'=>'10000000'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'author_id' => Yii::t('app', 'Автор'),
            'category_id' => Yii::t('app', 'Категория'),
            'image_id' => Yii::t('app', 'Изображение'),
            'is_commentable' => Yii::t('app', 'Разрешено комментировать'),
            'is_enabled' => Yii::t('app', 'Включено'),
            'title' => Yii::t('app', 'Заголовок'),
            'slug' => Yii::t('app', 'Алиас'),
            'annotation' => Yii::t('app', 'Аннотация'),
            'text' => Yii::t('app', 'Текст'),
            'meta_title' => Yii::t('app', 'Заголовок браузера'),
            'keywords' => Yii::t('app', 'Метатеги. Ключевые слова'),
            'description' => Yii::t('app', 'Метатеги. Описание'),
            'created_at' => Yii::t('app', 'Создано'),
            'updated_at' => Yii::t('app', 'Обновлено'),
            'file' => Yii::t('app', 'Файл изображения'),
            'category' => Yii::t('app', 'Название категории'),

        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'slugAttribute' => 'slug',
            ],
            'tagNames' => [
                'class' => Taggable::className(),
                'attribute' => 'tagNames',
                'name' => 'title',
                'frequency' => 'weight'
            ]
            // for different configurations, please see the code
            // we have created tables and relationship in order to
            // use defaults settings
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                // Да это новая запись (insert)
                $this->created_at = date('Y-m-d H:i:s');
                $this->author_id = Yii::$app->user->id;
            }
            $this->updated_at = date('Y-m-d H:i:s');
            return true;
        }
        return false;
    }


    public function extraFields()
    {
        return ['author', 'category'];
    }

    public function getFullImage() {
        return $this->image ? Yii::getAlias('@web') . '/images/articles/full/' . $this->image : '';
    }

    public function getThumbImage() {
        return $this->image ? Yii::getAlias('@web') . '/images/articles/thumbs/' . $this->image : '';
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     *  @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])->viaTable('{{%blog_article_via_tag}}', ['article_id' => 'id']);
    }

    public static function getArchived($limit = 12)
    {
        $q = "SELECT created_at, MONTH(created_at) as month, YEAR (created_at) as year
				FROM ".self::tableName()." as p
				WHERE is_enabled = 1
				GROUP BY year, month				
				ORDER BY year desc, month desc
				LIMIT :limit";

        $res =  Yii::$app->db->createCommand($q)
            ->bindValues(["limit"=>$limit])->queryAll();

        return ($res == null?[]:$res);
    }

    public static function getLast($limit = 12)
    {
        $models = self::find()->where('is_enabled = 1')->orderBy(['created_at' => SORT_DESC])->all();

        return $models;
    }


}

modules/blog/controllers/ArticleController.php
<?php

namespace app\modules\blog\controllers;

use Imagine\Image\Box;
use Yii;
use app\modules\blog\models\Article;
use app\modules\blog\models\ArticleSearch;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\UploadedFile;


/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{


    //public $layot = '//blog';
   

   

    public function behaviors()
    {
      
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => $this->module->adminRoles,
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'images-get' => [
                'class' => '\vova07\imperavi\actions\GetImagesAction',
                'url' => Url::to(['/'], true).'uploads/blog/', // Directory URL address, where files are stored.
                'path' => '@webroot/uploads/blog', // Or absolute path to directory where files are stored.
                'options' => ['only' => ['*.jpg', '*.jpeg', '*.png', '*.gif', '*.ico']], // These options are by default.
            ],
            'image-
            upload' => [
                'class' => '\vova07\imperavi\actions\UploadFileAction',
                'url' => Url::to(['/'], true).'uploads/blog/', // Directory URL address, where files are stored.
                'path' => '@webroot/uploads/blog', // Or absolute path to directory where files are stored.
            ],
            'files-get' => [
                'class' => 'vova07\imperavi\actions\GetFilesAction',
                'url' => Url::to(['/'], true).'uploads/blog/', // Directory URL address, where files are stored.
                'path' => '@webroot/uploads/blog', // Or absolute path to directory where files are stored.
            ],
            'file-upload' => [
                'class' => 'vova07\imperavi\actions\UploadFileAction',
                'url' => Url::to(['/'], true).'uploads/blog/', // Directory URL address, where files are stored.
                'path' => '@webroot/uploads/blog', // Or absolute path to directory where files are stored.
                'uploadOnlyImage' => false, // For any kind of files uploading.
            ],
            'file-delete' => [
                'class' => '\vova07\imperavi\actions\DeleteFileAction',
                'url' => Url::to(['/'], true).'uploads/blog/', // Directory URL address, where files are stored.
                'path' => '@webroot/uploads/blog', // Or absolute path to directory where files are stored.
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
       
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $image = UploadedFile::getInstance($model, 'file');
            if (!is_null($image)) {
                $model->image = $image->name;
                $path_parts = pathinfo($model->image);
                $ext = $path_parts['extension'];
                $model->image = "article_{$model->id}.{$ext}";
                $path = Yii::$app->basePath . '/web/images/articles/full/' . $model->image;
                $image->saveAs($path);
                $imagine = Image::getImagine();
                $image = $imagine->open($path);
                $image->resize(new Box(400, 300))->save(Yii::$app->basePath . '/web/images/articles/thumbs/' . $model->image, ['quality' => 70]);
                $model->save(false);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
//        $model->image = $model->image ? Yii::getAlias('@webroot') . $model->getFullImage() : '';

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $image = UploadedFile::getInstance($model, 'file');
            if (!is_null($image)) {
                $model->image = $image->name;
                $path_parts = pathinfo($model->image);
                $ext = $path_parts['extension'];
                $model->image = "article_{$model->id}.{$ext}";
                $path = Yii::$app->basePath . '/web/images/articles/full/' . $model->image;
                $image->saveAs($path);
                $imagine = Image::getImagine();
                $image = $imagine->open($path);
                $image->resize(new Box(400, 300))->save(Yii::$app->basePath . '/web/images/articles/thumbs/' . $model->image, ['quality' => 70]);
            }
            if ($model->save(false)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    public function actionDeleteImage($id)
    {
        $model = $this->findModel($id);
        unlink(Yii::$app->basePath . '/web/images/articles/full/' . $model->image);
        unlink(Yii::$app->basePath . '/web/images/articles/thumbs/' . $model->image);
        $model->image = '';
        $model->save();
        $success=true;
        return json_encode($success);
    }
    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/blog/views/article/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\selectize\SelectizeTextInput;
use yii\helpers\Url;
use vova07\imperavi\Widget;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\modules\blog\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model) ?>

    <?= $form->field($model, 'category_id')->dropDownList(\app\modules\blog\models\Category::getAllCategoryList(),[
        'prompt' => 'Выберите категорию'
    ]) ?>

    <?= $form->field($model, 'file')->widget(FileInput::classname(), [
        'options' => [
            'accept' => 'image/*',
            'multiple' => false,
        ],
        'pluginOptions' => [
            'showPreview' => true,
            'showRemove' => true,
            'showUpload' => true,
            'deleteUrl' => Url::toRoute(['article/delete-image', 'id' => $model->id]),
            'initialPreview' => $model->image ? $model->getFullImage() : false,
            'initialPreviewAsData'=>true,
            'overwriteInitial'=> false,
        ]
    ]); ?>

    <?= $form->field($model, 'is_commentable')->dropDownList(['Да', 'Нет']) ?>

    <?= $form->field($model, 'is_enabled')->dropDownList([1=>'Да', 0=>'Нет']) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tagNames')->widget(SelectizeTextInput::className(), [
        // calls an action that returns a JSON object with matched
        // tags
        'loadUrl' => ['tag/list'],
        'options' => ['class' => 'form-control'],
        'clientOptions' => [
            'plugins' => ['remove_button'],
            'valueField' => 'title',
            'labelField' => 'title',
            'searchField' => ['title'],
            'create' => true,
        ],
    ])->hint('Use commas to separate tags') ?>

    <?= $form->field($model, 'annotation')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'imageUpload' => Url::to(['article/image-upload']),
            'imageManagerJson' => Url::to(['article/images-get']),
            'fileUpload' => Url::to(['article/file-upload']),
            'fileManagerJson' => Url::to(['article/files-get']),
            'plugins' => [
                'imagemanager',
                'filemanager',
                'clips',
                'fullscreen',
            ],
            'clips' => [
                ['Lorem ipsum...', 'Lorem...'],
                ['red', '<span class="label-red">red</span>'],
                ['green', '<span class="label-green">green</span>'],
                ['blue', '<span class="label-blue">blue</span>'],
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'meta_title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'keywords')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/blog/views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\blog\models\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'author_id') ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'image_id') ?>

    <?= $form->field($model, 'is_commentable') ?>

    <?php // echo $form->field($model, 'is_enabled') ?>

    <?php // echo $form->field($model, 'title') ?>

    <?php // echo $form->field($model, 'slug') ?>

    <?php // echo $form->field($model, 'annotation') ?>

    <?php // echo $form->field($model, 'text') ?>

    <?php // echo $form->field($model, 'keywords') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/blog/views/article/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\blog\models\Article */

$this->title = Yii::t('app', 'Create Article');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Articles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/blog/views/article/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use app\assets\App2Asset;


App2Asset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\modules\blog\models\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Articles');
$this->params['breadcrumbs'][] = $this->title;


?>

    <?php GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'author_id',
                'filter' => \app\models\User::getFullList(),
                'value' => function($data) {
                    return !empty($data->author) ? $data->author->username : '';
                }
            ],
            [
                'attribute' => 'category_id',
                'filter' => \app\modules\blog\models\Category::getAllCategoryList(),
                'value' => function($data) {
                    return !empty($data->category) ? $data->category->title : '';
                }
            ],
            'title',
            'slug',
            'annotation:ntext',
            'created_at',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);?>

modules/blog/views/article/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\blog\models\Article */

$this->title = Yii::t('app', 'Update Article: ' . $model->title, [
    'nameAttribute' => '' . $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Articles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="article-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/blog/views/article/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\blog\models\Article */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Articles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'author.username',
            'category.title',
            'is_commentable',
            'is_enabled',
            'title',
            'slug',
            'meta_title',
            'keywords',
            'description',
            'created_at',
            'updated_at',
        ],
    ]) ?>

    <h1><?= $model->title ?></h1>
    <?php if ($model->image) { ?>
        <p><img src="<?= $model->getFullImage() ?>" style="width: 100%"></p>
    <?php } ?>
    <p><?= nl2br($model->annotation)  ?></p>
    <p><?= $model->text  ?></p>

</div>